<<<<<<< HEAD
name: 'Trigger Docker build on release'
=======
name: Trigger Docker build on release
>>>>>>> c86f945bdab2473f784e9ca5ecf8f1b0d9624886
on:
  release:
    types: [released]
jobs:
  curl:
<<<<<<< HEAD
    name: 'Trigger Docker build on release'
=======
>>>>>>> c86f945bdab2473f784e9ca5ecf8f1b0d9624886
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
    - name: curl
      run: |
        apk add curl bash
        curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" -H "Authorization: token ${{ secrets.TRAVIS_CI_TOKEN }}" -d '{"request":{"branch":"master"}}' https://api.travis-ci.com/repo/frappe%2Ffrappe_docker/requests
